# Generated by Django 2.2.28 on 2023-02-01 21:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0043_auto_20220913_1004"),
        ("weather", "0001_initial"),
        ("signage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveChannelPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="signage.Page",
                    ),
                ),
                (
                    "livechannel",
                    models.ForeignKey(
                        help_text="The streaming channel that should be displayed. Provided that a public stream is started in this location while this page is active.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video.LiveChannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Live channel page",
                "verbose_name_plural": "Live channel pages",
            },
            bases=("signage.page",),
        ),
        migrations.CreateModel(
            name="WeatherPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="signage.Page",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather.Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weather page",
                "verbose_name_plural": "Weather pages",
            },
            bases=("signage.page",),
        ),
        migrations.AlterModelOptions(
            name="campusonlineeventpage",
            options={
                "verbose_name": "CAMPUSonline event page",
                "verbose_name_plural": "CAMPUSonline event pages",
            },
        ),
        migrations.AlterModelOptions(
            name="htmlpage",
            options={"verbose_name": "HTML page", "verbose_name_plural": "HTML pages"},
        ),
        migrations.AlterModelOptions(
            name="imagepage",
            options={
                "verbose_name": "Image page",
                "verbose_name_plural": "Image pages",
            },
        ),
        migrations.AlterModelOptions(
            name="moviepage",
            options={
                "verbose_name": "Movie page",
                "verbose_name_plural": "Movie pages",
            },
        ),
        migrations.AlterModelOptions(
            name="pdfpage",
            options={"verbose_name": "PDF page", "verbose_name_plural": "PDF pages"},
        ),
        migrations.AlterModelOptions(
            name="restaurantpage",
            options={
                "verbose_name": "Restaurant page",
                "verbose_name_plural": "Restaurant pages",
            },
        ),
        migrations.AlterModelOptions(
            name="richtextpage",
            options={
                "verbose_name": "Rich text page",
                "verbose_name_plural": "Rich text pages",
            },
        ),
        migrations.AlterModelOptions(
            name="typo3eventpage",
            options={
                "verbose_name": "TYPO3 event page",
                "verbose_name_plural": "TYPO3 event pages",
            },
        ),
        migrations.AlterModelOptions(
            name="typo3newspage",
            options={
                "verbose_name": "TYPO3 news page",
                "verbose_name_plural": "TYPO3 news pages",
            },
        ),
        migrations.AlterModelOptions(
            name="websitepage",
            options={
                "verbose_name": "Website page",
                "verbose_name_plural": "Website pages",
            },
        ),
        migrations.AlterField(
            model_name="campusonlineeventpage",
            name="building",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="The building for which all events should be displayed.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="campusonline.Building",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="name",
            field=models.CharField(
                help_text="A canonical name for this page.", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="runtime",
            field=models.DurationField(
                default=datetime.timedelta(seconds=20),
                help_text="The time this page should be visible before it is replaced with the next page.",
            ),
        ),
        migrations.DeleteModel(
            name="LiveEventPage",
        ),
    ]
