# Generated by Django 2.2.28 on 2023-02-16 21:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import outpost.django.base.utils
import outpost.django.base.validators
import outpost.django.signage.validators


class Migration(migrations.Migration):

    dependencies = [
        ("signage", "0002_auto_20230201_2250"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="signage.Page",
                    ),
                ),
                (
                    "movie",
                    models.FileField(
                        upload_to=outpost.django.base.utils.Uuid4Upload,
                        validators=[
                            outpost.django.signage.validators.MediaContainerValidator(
                                audio_streams=0,
                                formats=("mp4",),
                                inlines=(
                                    outpost.django.signage.validators.MediaVideoValidator(
                                        codecs=("h264",),
                                        height=range(480, 1081),
                                        width=range(720, 1921),
                                    ),
                                ),
                                video_streams=1,
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Video page",
                "verbose_name_plural": "Video pages",
            },
            bases=("signage.page",),
        ),
        migrations.AlterField(
            model_name="imagepage",
            name="image",
            field=models.ImageField(
                upload_to=outpost.django.base.utils.Uuid4Upload,
                validators=[
                    outpost.django.base.validators.ImageValidator(
                        formats=("jpeg", "png", "webp"),
                        height=range(1080, 2160),
                        width=range(1920, 4096),
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="websitepage",
            name="url",
            field=models.URLField(
                validators=[django.core.validators.URLValidator(schemes=("https",))]
            ),
        ),
        migrations.DeleteModel(
            name="MoviePage",
        ),
    ]
