# Generated by Django 2.2.28 on 2023-02-16 21:10

from django.db import migrations, models
import outpost.django.base.utils
import outpost.django.base.validators
import outpost.django.signage.validators


class Migration(migrations.Migration):

    dependencies = [
        ("signage", "0003_auto_20230216_2204"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videopage",
            name="movie",
        ),
        migrations.AddField(
            model_name="videopage",
            name="video",
            field=models.FileField(
                default=1,
                help_text="Video to be used as a fullscreen page.",
                upload_to=outpost.django.base.utils.Uuid4Upload,
                validators=[
                    outpost.django.signage.validators.MediaContainerValidator(
                        audio_streams=0,
                        formats=("mp4",),
                        inlines=(
                            outpost.django.signage.validators.MediaVideoValidator(
                                codecs=("h264",),
                                height=range(480, 1081),
                                width=range(720, 1921),
                            ),
                        ),
                        video_streams=1,
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="htmlpage",
            name="content",
            field=models.TextField(
                help_text="Raw HTML can be used to construct more in-depth pages."
            ),
        ),
        migrations.AlterField(
            model_name="imagepage",
            name="image",
            field=models.ImageField(
                help_text="Image to be used as a fullscreen page.",
                upload_to=outpost.django.base.utils.Uuid4Upload,
                validators=[
                    outpost.django.base.validators.ImageValidator(
                        formats=("jpeg", "png", "webp"),
                        height=range(1080, 2160),
                        width=range(1920, 4096),
                    )
                ],
            ),
        ),
    ]
