# Generated by Django 2.2.28 on 2023-05-03 06:46

import datetime
from django.db import migrations, models
import outpost.django.base.utils
import outpost.django.signage.validators


class Migration(migrations.Migration):

    dependencies = [
        ("signage", "0006_restaurantpage_restaurant_runtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdfpage",
            name="pdf",
            field=models.FileField(
                help_text="PDF file to be used as a fullscreen page.",
                upload_to=outpost.django.base.utils.Uuid4Upload,
                validators=[
                    outpost.django.signage.validators.PDFValidator(pages=range(1, 20))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="restaurantpage",
            name="restaurant_runtime",
            field=models.DurationField(default=datetime.timedelta(seconds=30)),
        ),
    ]
