# Generated by Django 2.2.28 on 2023-08-23 10:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import outpost.django.base.utils
import outpost.django.base.validators


class Migration(migrations.Migration):

    dependencies = [
        ("signage", "0007_auto_20230503_0846"),
    ]

    operations = [
        migrations.AddField(
            model_name="display",
            name="config",
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="display",
            name="screen",
            field=models.ImageField(
                null=True,
                upload_to=outpost.django.base.utils.Uuid4Upload,
                validators=[
                    outpost.django.base.validators.FileValidator(
                        mimetypes=["image/png"]
                    )
                ],
            ),
        ),
    ]
