# Generated by Django 2.2.28 on 2023-09-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signage", "0008_auto_20230823_1235"),
    ]

    operations = [
        migrations.AddField(
            model_name="resolution",
            name="dpi",
            field=models.PositiveIntegerField(blank=True, default=72, null=True),
        ),
        migrations.AddField(
            model_name="resolution",
            name="scale",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
