# Generated by Django 2.2.28 on 2023-09-19 12:33

from django.db import migrations, models
import django.db.models.deletion
import outpost.django.base.utils


class Migration(migrations.Migration):

    dependencies = [
        ("signage", "0009_auto_20230919_1113"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdfpage",
            name="pages",
        ),
        migrations.CreateModel(
            name="PDFPageRender",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page", models.PositiveIntegerField()),
                (
                    "image",
                    models.ImageField(upload_to=outpost.django.base.utils.Uuid4Upload),
                ),
                (
                    "pdf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="signage.PDFPage",
                    ),
                ),
            ],
        ),
    ]
