# Generated by Django 2.2.28 on 2025-07-18 12:51

from django.db import migrations, models
import outpost.django.base.utils
import outpost.django.signage.validators


class Migration(migrations.Migration):

    dependencies = [
        ("signage", "0011_remove_display_screen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdfpage",
            name="pdf",
            field=models.FileField(
                help_text="PDF file to be used as a fullscreen page.",
                upload_to=outpost.django.base.utils.Uuid4Upload,
                validators=[
                    outpost.django.signage.validators.PDFValidator(pages=range(1, 50))
                ],
            ),
        ),
    ]
