# Generated by Django 5.2.16 on 2026-09-17 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("signage", "0012_auto_20250718_1451"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campusonlineeventpage",
            options={
                "get_latest_by": "modified",
                "verbose_name": "CAMPUSonline event page",
                "verbose_name_plural": "CAMPUSonline event pages",
            },
        ),
        migrations.AlterModelOptions(
            name="htmlpage",
            options={
                "get_latest_by": "modified",
                "verbose_name": "HTML page",
                "verbose_name_plural": "HTML pages",
            },
        ),
        migrations.AlterModelOptions(
            name="imagepage",
            options={
                "get_latest_by": "modified",
                "verbose_name": "Image page",
                "verbose_name_plural": "Image pages",
            },
        ),
        migrations.AlterModelOptions(
            name="livechannelpage",
            options={
                "get_latest_by": "modified",
                "verbose_name": "Live channel page",
                "verbose_name_plural": "Live channel pages",
            },
        ),
        migrations.AlterModelOptions(
            name="pdfpage",
            options={
                "get_latest_by": "modified",
                "verbose_name": "PDF page",
                "verbose_name_plural": "PDF pages",
            },
        ),
        migrations.AlterModelOptions(
            name="restaurantpage",
            options={
                "get_latest_by": "modified",
                "verbose_name": "Restaurant page",
                "verbose_name_plural": "Restaurant pages",
            },
        ),
        migrations.AlterModelOptions(
            name="richtextpage",
            options={
                "get_latest_by": "modified",
                "verbose_name": "Rich text page",
                "verbose_name_plural": "Rich text pages",
            },
        ),
        migrations.AlterModelOptions(
            name="typo3eventpage",
            options={
                "get_latest_by": "modified",
                "verbose_name": "TYPO3 event page",
                "verbose_name_plural": "TYPO3 event pages",
            },
        ),
        migrations.AlterModelOptions(
            name="typo3newspage",
            options={
                "get_latest_by": "modified",
                "verbose_name": "TYPO3 news page",
                "verbose_name_plural": "TYPO3 news pages",
            },
        ),
        migrations.AlterModelOptions(
            name="videopage",
            options={
                "get_latest_by": "modified",
                "verbose_name": "Video page",
                "verbose_name_plural": "Video pages",
            },
        ),
        migrations.AlterModelOptions(
            name="weatherpage",
            options={
                "get_latest_by": "modified",
                "verbose_name": "Weather page",
                "verbose_name_plural": "Weather pages",
            },
        ),
        migrations.AlterModelOptions(
            name="websitepage",
            options={
                "get_latest_by": "modified",
                "verbose_name": "Website page",
                "verbose_name_plural": "Website pages",
            },
        ),
        migrations.AlterField(
            model_name="display",
            name="config",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
